sudo: required
services:
  - docker

before_install:
  - docker build -t theautonater801/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true theautonater801/react-test npm test

after_success:
  - docker build -t theautonater801/multi-client ./client
  - docker build -t theautonater801/multi-nginx ./nginx
  - docker build -t theautonater801/multi-server ./server
  - docker build -t theautonater801/multi-worker ./worker
